version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kalamna-api
    ports:
      - "8000:8000"
    environment: {}
      
      #DATABASE_URL: "${DATABASE_URL}"

      # JWT config
      #JWT_SECRET: "${JWT_SECRET}"
      #JWT_ALGORITHM: "${JWT_ALGORITHM:-HS256}"

      # Optional other envs
      # APP_ENV: "production"

    # Uncomment this during development only:
    # volumes:
    #   - .:/app
    #   - /app/__pycache__
    #   - /app/app/__pycache__
    
    # Restart policy for production environments
    restart: unless-stopped


